Using TensorFlow backend.
Traceback (most recent call last):
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 2304 elements to shape [48] (48 elements) for 'FunctionOutputReshapeToConstraintShape/Reshape' (op: 'Reshape') with input shapes: [48,48], [1] and with input tensors computed as partial shapes: input[1] = [48].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./training-latplan2.py", line 84, in <module>
    lyr.Constraint("forall x: equals(x, x)", 1.)
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/lyrics.py", line 380, in __init__
    self.root.compile()
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/parser.py", line 556, in compile
    super(ForAll, self).compile()
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/parser.py", line 30, in compile
    i.compile()
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/parser.py", line 379, in compile
    self.tensor = tf.reshape(self.tensor, fun_shape)
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 131, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 8115, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 2304 elements to shape [48] (48 elements) for 'FunctionOutputReshapeToConstraintShape/Reshape' (op: 'Reshape') with input shapes: [48,48], [1] and with input tensors computed as partial shapes: input[1] = [48].
